/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiladoruniajc;

import compiladoruniajc.LogicaSQL.OperacionDelete;
import compiladoruniajc.LogicaSQL.OperacionUpdate;
import compiladoruniajc.LogicaSQL.OperacionInsert;
import compiladoruniajc.LogicaSQL.OperacionSelect;
import java.util.ArrayList;
import compiladoruniajc.LogicaSQL.Tokens;

/**
 *
 * @author Jonathan
 */
public class JICompiladorSQL extends javax.swing.JInternalFrame {

    
   String strInstruccionSQL = "";
 
    Tokens tokens;
    
    private ArrayList codigo = new ArrayList();
    public JICompiladorSQL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_ejecutar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_source = new javax.swing.JTextArea();
        jTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_area_compi = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_area_eje = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Compilador SQL UNIAJC");
        setToolTipText("");

        jToolBar1.setRollover(true);

        btn_ejecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compiladoruniajc/recursos/flecha.png"))); // NOI18N
        btn_ejecutar.setToolTipText("Run");
        btn_ejecutar.setFocusable(false);
        btn_ejecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ejecutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ejecutarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_ejecutar);

        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compiladoruniajc/recursos/limpiar.png"))); // NOI18N
        btn_limpiar.setToolTipText("Clean");
        btn_limpiar.setFocusable(false);
        btn_limpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_limpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_limpiar);

        ta_source.setColumns(20);
        ta_source.setRows(5);
        jScrollPane1.setViewportView(ta_source);

        jTabbedPane1.addTab("Source", jScrollPane1);

        txt_area_compi.setBackground(new java.awt.Color(0, 0, 0));
        txt_area_compi.setColumns(20);
        txt_area_compi.setForeground(new java.awt.Color(51, 255, 51));
        txt_area_compi.setRows(5);
        jScrollPane2.setViewportView(txt_area_compi);

        jTabbedPane.addTab("Compilador", jScrollPane2);

        txt_area_eje.setBackground(new java.awt.Color(0, 0, 0));
        txt_area_eje.setColumns(20);
        txt_area_eje.setForeground(new java.awt.Color(51, 255, 51));
        txt_area_eje.setRows(5);
        jScrollPane3.setViewportView(txt_area_eje);

        jTabbedPane.addTab("Ejecución", jScrollPane3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addComponent(jTabbedPane))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        ta_source.setText("");
        txt_area_compi.setText("");
        txt_area_eje.setText("");
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ejecutarActionPerformed
                   jTabbedPane.setSelectedIndex(1);
 
             try
 
             {
 
             //Obtener el texto del JTextArea
 
             strInstruccionSQL = ta_source.getText() ;
 
             //strInstruccionSQL+=";";        //Para que el usuario no tenga que escribir ; en el JTextArea
 
             //Indicar que la cadena SQL es el texto del JTextArea
 
             tokens = new Tokens(strInstruccionSQL);
 
             tokens.obtenerToken();         //Lee el primer token de la cadena SQL
 
             //Convertimos la primera palabra leida a minusculas
 
             String strPrimerToken = tokens.token.toString().toUpperCase();
 
             //Comprobar si es alguna de las 4 operaciones permitidas
 
             txt_area_eje.setText("");    //En cada clic borrar los mensajes anteriores
 
             txt_area_compi.setText("");    //En cada clic borrar los mensajes anteriores
 
             //Comprobar si es una de las 4 operaciones SQL que se implementaran en el DDBMS
 
             if(strPrimerToken.equals("INSERT") || strPrimerToken.equals("DELETE") || strPrimerToken.equals("UPDATE") || strPrimerToken.equals("SELECT"))
 
             {
 
                 txt_area_eje.append("Es una operacion: " + strPrimerToken.toString()+"\n");
 
                 if(strPrimerToken.equals("INSERT"))
 
                 {
 
                     OperacionInsert insert1 = new OperacionInsert(strInstruccionSQL);
 
                     insert1.analizar();
 
                 }
 
                 else if(strPrimerToken.equals("DELETE"))
 
                     {
 
                        OperacionDelete delete1 = new OperacionDelete(strInstruccionSQL);
 
                         delete1.analizar();
 
                     }
 
                     else if(strPrimerToken.equals("UPDATE"))
 
                         {
 
                             OperacionUpdate update1 = new OperacionUpdate(strInstruccionSQL);
 
                              update1.analizar();
 
                         }
 
                         else if(strPrimerToken.equals("SELECT"))
 
                             {
 
                                 OperacionSelect select1 = new OperacionSelect(strInstruccionSQL);
 
                                 select1.analizar();
 
                             }
 
             }
 
             else
 
             {
 
                if(strPrimerToken.length()== 0 || strPrimerToken.equals(";") )
 
                    txt_area_eje.append("No ha escrito nada");
 
                else if(strPrimerToken.length() > 0)
                
                 txt_area_eje.append("\n'"+ strPrimerToken +"\'"+"<-- No es una Operacion SQL valida");
 
             }
 
             }
 
             catch(Exception e)
 
             {
 
             }
    }//GEN-LAST:event_btn_ejecutarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ejecutar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea ta_source;
    public static javax.swing.JTextArea txt_area_compi;
    public static javax.swing.JTextArea txt_area_eje;
    // End of variables declaration//GEN-END:variables


}
