/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiladoruniajc;

import de.javasoft.plaf.synthetica.SyntheticaAluOxideLookAndFeel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Jonathan
 */
public class MDIPrincipal extends javax.swing.JFrame {

   static String us="admin";
   static String con="admin";
   
   private JICompilador compilador;
   private JICompiladorSQL compiladorSQL;
    public MDIPrincipal() {
        initComponents();
        
         escritorio.setBorder(new Imagenfondo());
         
        Color c1=new Color(66,111,166);
        Color c2=new Color(102,174,118);
        JPColor miColor=new JPColor(c1,c2);
        miColor.setSize(this.getSize());
        panel.add(miColor);
    }

     @SuppressWarnings("unchecked")
    @Override
    public Image getIconImage() 
      {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("compiladorUNIAJC/recursos/icono2.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDInicio = new javax.swing.JDialog();
        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        pf_contra = new javax.swing.JPasswordField();
        btn_ingresar = new javax.swing.JButton();
        btn_salir1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jtoolbar = new javax.swing.JToolBar();
        lb_us = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_compi = new javax.swing.JButton();
        btn_compsql = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Compilador = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmenuacercade = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        JDInicio.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        JDInicio.setUndecorated(true);
        JDInicio.setResizable(false);

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 0));
        jLabel1.setText("ENTRADA AL SISTEMA");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Usuario *");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Contraseña *");

        pf_contra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pf_contraKeyPressed(evt);
            }
        });

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        btn_salir1.setText("Salir");
        btn_salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compiladoruniajc/recursos/llave.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ingresar)
                        .addGap(53, 53, 53)
                        .addComponent(btn_salir1)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ingresar)
                    .addComponent(btn_salir1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JDInicioLayout = new javax.swing.GroupLayout(JDInicio.getContentPane());
        JDInicio.getContentPane().setLayout(JDInicioLayout);
        JDInicioLayout.setHorizontalGroup(
            JDInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JDInicioLayout.setVerticalGroup(
            JDInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JDInicioLayout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador UNIAJC");

        jtoolbar.setRollover(true);

        lb_us.setText("Usuario");
        jtoolbar.add(lb_us);
        jtoolbar.add(jSeparator1);

        btn_compi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compiladoruniajc/recursos/java.png"))); // NOI18N
        btn_compi.setToolTipText("Compilador JAVA");
        btn_compi.setFocusable(false);
        btn_compi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_compi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_compi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_compiActionPerformed(evt);
            }
        });
        jtoolbar.add(btn_compi);

        btn_compsql.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compiladoruniajc/recursos/sql_1.png"))); // NOI18N
        btn_compsql.setToolTipText("Compilador SQL");
        btn_compsql.setFocusable(false);
        btn_compsql.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_compsql.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_compsql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_compsqlActionPerformed(evt);
            }
        });
        jtoolbar.add(btn_compsql);

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compiladoruniajc/recursos/salir.png"))); // NOI18N
        btn_salir.setFocusable(false);
        btn_salir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_salir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jtoolbar.add(btn_salir);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtoolbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jtoolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 173, Short.MAX_VALUE))
        );
        escritorio.setLayer(jtoolbar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("File");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        Compilador.setText("Compilador");
        Compilador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompiladorActionPerformed(evt);
            }
        });
        jMenu2.add(Compilador);

        jMenuItem2.setText("Compilador SQL");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jmenuacercade.setText("Acerca de");

        jMenuItem3.setText("Acerca de");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmenuacercade.add(jMenuItem3);

        jMenuBar1.add(jmenuacercade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
         int respuesta=javax.swing.JOptionPane.showConfirmDialog(rootPane, "Esta seguro de que desea salir ?");
        if(respuesta == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btn_salirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         int respuesta=javax.swing.JOptionPane.showConfirmDialog(rootPane, "Esta seguro de que desea salir ?");
        if(respuesta == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void pf_contraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf_contraKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            this.logueo();
        }
    }//GEN-LAST:event_pf_contraKeyPressed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        this.logueo();
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salir1ActionPerformed

    private void btn_compiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_compiActionPerformed
       if(estacerrado(compilador))
        {
             
            compilador=new JICompilador();
            escritorio.add(compilador);
            Dimension tamanoEscritorio=escritorio.getSize();
            Dimension framesize=compilador.getSize();
            compilador.setLocation((tamanoEscritorio.width - framesize.width)/2, (tamanoEscritorio.height - framesize.height)/2) ;
            compilador.show();
       
        }else
        {
            JOptionPane.showMessageDialog(this, "La ventana ya esta abierta");
        }
    }//GEN-LAST:event_btn_compiActionPerformed

    private void CompiladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompiladorActionPerformed
        if(estacerrado(compilador))
        {
             
            compilador=new JICompilador();
            escritorio.add(compilador);
            Dimension tamanoEscritorio=escritorio.getSize();
            Dimension framesize=compilador.getSize();
            compilador.setLocation((tamanoEscritorio.width - framesize.width)/2, (tamanoEscritorio.height - framesize.height)/2) ;
            compilador.show();
       
        }else
        {
            JOptionPane.showMessageDialog(this, "La ventana ya esta abierta");
        }
    }//GEN-LAST:event_CompiladorActionPerformed

    private void btn_compsqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_compsqlActionPerformed
        if(estacerrado(compiladorSQL))
        {
             
            compiladorSQL=new JICompiladorSQL();
            escritorio.add(compiladorSQL);
            Dimension tamanoEscritorio=escritorio.getSize();
            Dimension framesize=compiladorSQL.getSize();
            compiladorSQL.setLocation((tamanoEscritorio.width - framesize.width)/2, (tamanoEscritorio.height - framesize.height)/2) ;
            compiladorSQL.show();
       
        }else
        {
            JOptionPane.showMessageDialog(this, "La ventana ya esta abierta");
        }
    }//GEN-LAST:event_btn_compsqlActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         if(estacerrado(compiladorSQL))
        {
             
            compiladorSQL=new JICompiladorSQL();
            escritorio.add(compiladorSQL);
            Dimension tamanoEscritorio=escritorio.getSize();
            Dimension framesize=compiladorSQL.getSize();
            compiladorSQL.setLocation((tamanoEscritorio.width - framesize.width)/2, (tamanoEscritorio.height - framesize.height)/2) ;
            compiladorSQL.show();
       
        }else
        {
            JOptionPane.showMessageDialog(this, "La ventana ya esta abierta");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       JOptionPane.showMessageDialog(this, "UNIAJC \n Compilador JAVA y SQL \n Realizado por: \n- Jonathan Arteaga \n - Jorge Castaño \n - Hector Guampe ");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ParseException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("de.javasoft.plaf.synthetica.SyntheticaBlueLightLookAndFeel;".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaAluOxideLookAndFeel;");
                    break;
                }
            }
            UIManager.setLookAndFeel(new SyntheticaAluOxideLookAndFeel());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MDIPrincipal().setVisible(false);
                new Thread(new Splash()).start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Compilador;
    private javax.swing.JDialog JDInicio;
    private javax.swing.JButton btn_compi;
    private javax.swing.JButton btn_compsql;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_salir1;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JMenu jmenuacercade;
    private javax.swing.JToolBar jtoolbar;
    private javax.swing.JLabel lb_us;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField pf_contra;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables

  private boolean estacerrado(Object obj)
{
    JInternalFrame[] activos=escritorio.getAllFrames();
    boolean cerrado=true;
    int i=0;
    while (i<activos.length && cerrado)
    {
        if(activos[i]==obj)
        {
            cerrado=false;
        }
        i++;
    }
    return cerrado;
    
}

 public void iniciarSistema()
 {
     JDInicio.pack();
     JDInicio.setLocationRelativeTo(null);
     JDInicio.setVisible(true);
     JDInicio.setResizable(false);
 }
 
 
  public void logueo()
 {
     
        
         
                 
         int level=0;
         String usuario=txt_usuario.getText();
         String contra=String.valueOf(pf_contra.getPassword());
         
         if(us.equals(usuario) && con.equals(contra))
         {
             JDInicio.dispose();
             txt_usuario.setText("");
             pf_contra.setText("");
             
             lb_us.setText(usuario);
             
             this.setVisible(true);
         }
         
            else
         {
             JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos. \n Intentelo de nuevo", "Mensaje Error", JOptionPane.ERROR_MESSAGE);
         }
 }

}
